# ========================================================================== #
#     CONFIGURAÇÃO DOCKER COMPOSE PARA O AMBIENTE DE DESENVOLVIMENTO         #
# ========================================================================== #
# Este arquivo orquestra a aplicação Docker multi-contêiner. Ele define
# os serviços (como a API e o banco de dados), as redes e os volumes
# necessários para executar a pilha completa da aplicação.

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge