"""Adiciona campos de logistica ao produto

Revision ID: 8081ca856954
Revises: 4bdf71ce0028
Create Date: 2025-06-28 22:47:45.547806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8081ca856954'
down_revision: Union[str, Sequence[str], None] = '4bdf71ce0028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('weight_kg', sa.Float(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('height_cm', sa.Float(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('width_cm', sa.Float(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('length_cm', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'length_cm')
    op.drop_column('products', 'width_cm')
    op.drop_column('products', 'height_cm')
    op.drop_column('products', 'weight_kg')
    # ### end Alembic commands ###
